services:
  Neusta\Pimcore\FixtureBundle\Command\LoadFixturesCommand:
    arguments:
      $container: '@Symfony\Component\DependencyInjection\ContainerInterface'
    tags:
      - { name: 'console.command' }
