services:
  NspPimcore\FixtureBase\Command\LoadFixturesCommand:
    arguments:
      $container: '@Symfony\Component\DependencyInjection\ContainerInterface'
    tags:
      - { name: 'console.command' }

  NspPimcore\Fixtures\Index\Factory\IndexFactory:
    class: NspPimcore\Fixtures\Index\Factory\IndexFactory
    public: true # will be used in Fixtures to create indexes

  NspPimcore\Fixtures\Index\Factory\FilterFactory:
    class: NspPimcore\Fixtures\Index\Factory\FilterFactory
    public: true # will be used in Fixtures to create filters
